# Deployment for FastAPI app (GLiNER)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gliner-ner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gliner-ner-app
  template:
    metadata:
      labels:
        app: gliner-ner-app
    spec:
      containers:
        - name: gliner-ner-app
          image: vybhavnca/gliner-ner-app:latest
          env:
            - name: POSTGRES_USERNAME
              value: "vybhav"
            - name: POSTGRES_PASSWORD
              value: "sivam123"
            - name: POSTGRES_DBNAME
              value: "glinerdb"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: MODEL_NAME
              value: "urchade/gliner_medium-v2.1"
            - name: BACKEND_HOST
              value: "localhost"
            - name: BACKEND_PORT
              value: "8000"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          ports:
            - containerPort: 8000  # FastAPI port
---
# Deployment for Streamlit app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: your-streamlit-image:latest
          env:
            - name: STREAMLIT_BACKEND_HOST
              value: "gliner-ner-service"
            - name: STREAMLIT_BACKEND_PORT
              value: "8000"
          ports:
            - containerPort: 8501
---
# Service for FastAPI (GLiNER)
apiVersion: v1
kind: Service
metadata:
  name: gliner-ner-service
spec:
  selector:
    app: gliner-ner-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Expose FastAPI app on port 80 (or any desired port)
  type: LoadBalancer
---
# Service for Streamlit app
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501  # Expose Streamlit app on port 80 (or any desired port)
  type: LoadBalancer
